#!/usr/bin/env bash
# Spend Track setup: writes DB credentials OUTSIDE the repo, installs deps,
# downloads the AWS RDS CA bundle, runs migrations, and optionally creates an account.
#
#   npm run setup            # interactive
#   SPEND_TRACK_ENV_FILE=/path/.env npm run setup   # custom location
set -euo pipefail

cd "$(dirname "$0")/.."
CONFIG_DIR="${SPEND_TRACK_CONFIG_DIR:-$HOME/.config/spend_track}"
ENV_FILE="${SPEND_TRACK_ENV_FILE:-$CONFIG_DIR/.env}"
CA_URL="https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem"
CA_FILE="$(dirname "$ENV_FILE")/rds-global-bundle.pem"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
ask()  { # ask VAR "Prompt" default
  local __v; read -r -p "  $2${3:+ [$3]}: " __v || true
  printf -v "$1" '%s' "${__v:-${3:-}}"
}

bold "1. Checking Node.js"
command -v node >/dev/null || die "Node.js is not installed (need v21+)."
node -e 'process.exit(+process.versions.node.split(".")[0] >= 21 ? 0 : 1)' || die "Node $(node -v) is too old; need v21+."
ok "node $(node -v)"

bold "2. Database credentials"
case "$ENV_FILE" in "$PWD"/*) die "Refusing to store secrets inside the project ($ENV_FILE).";; esac
reuse=n
if [[ -f "$ENV_FILE" ]]; then
  read -r -p "  $ENV_FILE exists. Keep it? [Y/n]: " keep || true
  [[ "${keep:-Y}" =~ ^[Nn] ]] || reuse=y
fi
if [[ $reuse == y ]]; then
  ok "using existing $ENV_FILE"
else
  ask DB_HOST "MySQL host" "${DB_HOST:-}"
  [[ -n "$DB_HOST" ]] || die "Host is required."
  ask DB_PORT "Port" "${DB_PORT:-3306}"
  ask DB_USER "User" "${DB_USER:-admin}"
  read -r -s -p "  Password: " DB_PASSWORD || true; echo
  [[ -n "$DB_PASSWORD" ]] || die "Password is required."
  [[ "$DB_PASSWORD" != *"'"* ]] || die "Passwords containing a single quote aren't supported in .env; set DB_PASSWORD in the environment instead."
  ask DB_NAME "Database name" "${DB_NAME:-spend_track}"
  ask DB_SSL  "TLS to database (required/off)" "${DB_SSL:-required}"
  ask PORT    "Local web server port" "${PORT:-3000}"

  mkdir -p "$(dirname "$ENV_FILE")"
  chmod 700 "$(dirname "$ENV_FILE")"
  ( umask 077
    cat > "$ENV_FILE" <<EOF
# Spend Track secrets. Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep this file out of git. Permissions should be 600.
DB_HOST='$DB_HOST'
DB_PORT='$DB_PORT'
DB_USER='$DB_USER'
DB_PASSWORD='$DB_PASSWORD'
DB_NAME='$DB_NAME'
DB_SSL='$DB_SSL'
DB_SSL_CA='$CA_FILE'
PORT='$PORT'
EOF
  )
  chmod 600 "$ENV_FILE"
  ok "wrote $ENV_FILE (mode 600)"
fi

bold "3. TLS certificate for AWS RDS"
if [[ -s "$CA_FILE" ]]; then ok "found $CA_FILE"
else
  curl -fsSL "$CA_URL" -o "$CA_FILE" || die "Could not download $CA_URL"
  ok "downloaded RDS CA bundle to $CA_FILE"
fi

bold "4. Installing dependencies"
npm install --no-audit --no-fund --loglevel=error || die "npm install failed. If npm mentions root-owned files, run: sudo chown -R \$(id -u):\$(id -g) ~/.npm"
ok "dependencies installed"

bold "5. Connecting and migrating"
export SPEND_TRACK_ENV_FILE="$ENV_FILE"
node scripts/migrate.js || die "Migration failed. Check host, password, and that your IP is allowed by the RDS security group."
ok "database ready"

bold "6. Account (optional)"
read -r -p "  Create a login now? [y/N]: " mk || true
if [[ "${mk:-N}" =~ ^[Yy] ]]; then
  ask ST_NAME  "Name" "Demo User"
  ask ST_EMAIL "Email" "demo@spendtrack.local"
  read -r -s -p "  Password (8+ chars): " ST_PASSWORD || true; echo
  read -r -p "  Load sample transactions? [Y/n]: " smp || true
  ST_NAME="$ST_NAME" ST_EMAIL="$ST_EMAIL" ST_PASSWORD="$ST_PASSWORD" ST_SAMPLE="${smp:-Y}" node scripts/create-user.js
fi

echo
bold "Done. Start the app with:  npm start"
